add processing result service
rbkmoney/fraudbusters-proto pull request #26
Opened 2021-07-07 08:22 UTC by ggmaleva

2021-07-07 08:58 UTC, strug requested changes

2021-07-07 08:58 UTC, strug commented on proto/fraudbusters.thrift
> +enum FilterField {
кажется не вижу смысла в enum, при реализации будет больше гемороя, а так как протокол бинарный и так можно очень легко добавлять новые поля. Поэтому думаю структурой п не списком с enum будет лучше

2021-07-07 08:58 UTC, strug commented on proto/fraudbusters.thrift
> +struct ResultFilter {
+ не вижу тут полей для реализации пегинации

2021-07-07 08:58 UTC, strug commented on proto/fraudbusters.thrift
> +service ProcessingResultService {
Кажется мы уходим от процессинга, назвал бы HistoryDataService ну или можем обсудить со всеми

2021-07-07 08:58 UTC, strug commented on proto/fraudbusters.thrift
> +    ProcessingResult getResult()
вот такое точн лучше не делать) нужен один метод с фильтрацией и пегинацией

2021-07-07 08:58 UTC, strug commented on proto/fraudbusters.thrift
> +    ProcessingResult getFilteredResult(1: list<ResultFilter> filters)
Не понял почему результат не список? и опять для пегинации надо будет добавить вспомогательные поля в ответ

2021-07-07 10:21 UTC, ggmaleva commented on proto/fraudbusters.thrift
> +    ProcessingResult getFilteredResult(1: list<ResultFilter> filters)
добавил

2021-07-07 10:21 UTC, ggmaleva commented on proto/fraudbusters.thrift
> +    ProcessingResult getResult()
оставил один

2021-07-07 10:23 UTC, ggmaleva commented on proto/fraudbusters.thrift
> +service ProcessingResultService {
Пока переименовал в HistoricalDataService. Но, мне кажется, это немного не то. Еще б обсудил.

2021-07-07 10:24 UTC, ggmaleva commented on proto/fraudbusters.thrift
> +struct ResultFilter {
их здесь и не будет, будет отдельный Page. Добавил.

2021-07-07 10:55 UTC, ggmaleva commented on proto/fraudbusters.thrift
> +enum FilterField {
поменял на union и struct

2021-07-07 12:11 UTC, strug commented on proto/fraudbusters.thrift
> +union Filter {
в таком виде, можно только 1 фильтр за раз передать, нужна struct

2021-07-07 12:11 UTC, strug commented on proto/fraudbusters.thrift
> +}
ну и вот это все тож не нужно тогда

2021-07-07 12:11 UTC, strug commented on proto/fraudbusters.thrift
> +struct HistoricalData {
сервис норм теперь, а вот это скорее Payment -> PaymentResult -> getPayments

2021-07-07 14:56 UTC, ggmaleva commented on proto/fraudbusters.thrift
> +struct HistoricalData {
Payment уже есть, поправил на PaymentInfo

2021-07-07 15:42 UTC, ggmaleva commented on proto/fraudbusters.thrift
> +union Filter {
поменял на struct

2021-07-07 15:42 UTC, ggmaleva commented on proto/fraudbusters.thrift
> +}
убрал

2021-07-08 06:41 UTC, strug approved these changes

2021-07-08 07:04 UTC, mr-impossibru commented on proto/fraudbusters.thrift
> +service ProcessingResultService {
Мне кажется в самый раз название

2021-07-08 07:06 UTC, mr-impossibru approved these changes
Единственный комментарий - у нас тут очень старая damsel, по хорошему её поднять надо, но это скорее в рамках отдельной задачи надо решать :)

LGTM

2021-07-08 08:48 UTC, D-Baykov commented on proto/fraudbusters.thrift
> +    2:  required MerchantInfo merchant
субъективщина, но я бы сделал merchant_info все-таки

2021-07-08 08:48 UTC, D-Baykov commented on proto/fraudbusters.thrift
> +    5:  required ID id
по негласной традиции перенес бы на 1 место)

2021-07-08 08:48 UTC, D-Baykov commented on proto/fraudbusters.thrift
> +    7:  optional ClientInfo client
тут бы сделал client_info (субъективно)

2021-07-08 08:48 UTC, D-Baykov commented on proto/fraudbusters.thrift
> +    8:  required string status
статус лучше в объект перенести, чтобы в дальнейшем было проще что-то в него добавить

2021-07-08 08:48 UTC, D-Baykov commented on proto/fraudbusters.thrift
> +    1: optional string party
party_id, чтобы по аналогии

2021-07-08 08:48 UTC, D-Baykov commented on proto/fraudbusters.thrift
> +    2: optional string shop
shop_id, наверное

2021-07-08 08:50 UTC, D-Baykov commented on proto/fraudbusters.thrift
> +struct Filter {
у нас там payment_id это invoice_id + "." + payment_id?

2021-07-08 11:26 UTC, ggmaleva commented on proto/fraudbusters.thrift
> +struct Filter {
добавил

2021-07-08 11:43 UTC, mr-impossibru approved these changes

2021-07-08 11:54 UTC, strug commented on proto/fraudbusters.thrift
> +struct Filter {
> у нас там payment_id это invoice_id + "." + payment_id?

да я абстрагировал от нашей модели вроде

2021-07-08 14:45 UTC, merged